CREATE TABLE IF NOT EXISTS "UserProfile" (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES "User"(id) ON DELETE CASCADE,
  phone TEXT DEFAULT NULL,
  address TEXT DEFAULT NULL,
  city TEXT DEFAULT NULL,
  occupation TEXT DEFAULT NULL,
  employer TEXT DEFAULT NULL,
  education_level TEXT DEFAULT NULL,
  education_institution TEXT DEFAULT NULL,
  education_career TEXT DEFAULT NULL,
  cv_url TEXT DEFAULT NULL,
  skills TEXT DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
